name: Run Linters

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

permissions:
    contents: write
jobs:
    pylint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.13.0-rc.1'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip

                  # Checks if requirements.txt already exists, then creates it if it doesn't
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 

                  # Install pylint
                  pip install pylint
                  
            - name: Run Pylint
              run: pylint ./hw2  # Runs pylint on all files in the repository.
    
