name: Run Tests

on:
    workflow_run:
        workflows: ["Run Linters"]
        types:
            - completed

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                  python-version: "3.13.0-rc.1"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip

                  # Checks if requirements.txt already exists, then creates it if it doesn't
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Test with pytest
              run: |
                  pip install pytest pytest-cov
                  pytest --cov=HW1 HW1/tests/
            - name: Coveralls GitHub Action
              if: success() || failure()
              uses: coverallsapp/github-action@v2.3.0
